services:
  phpbbmodders.banlist.controller.main:
    class: phpbbmodders\banlist\controller\main_controller
    arguments:
      - "@request"
      - "@config"
      - "@pagination"
      - "@dbal.conn"
      - "@auth"
      - "@template"
      - "@user"
      - "@controller.helper"
      - "%core.root_path%"
      - "%core.php_ext%"
      - "%core.table_prefix%"
  
  phpbbmodders.banlist.main_listener:
    class: phpbbmodders\banlist\event\main_listener
    arguments:
      - "@phpbbmodders.banlist.controller.main"
      - "@config"
      - "@request"
      - "@dbal.conn"
      - "@auth"
      - "@template"
      - "@user"
      - "%core.root_path%"
    tags:
      - { name: event.listener }

